name: 'Build & Deploy'

concurrency:
  group: prod_deploy
  cancel-in-progress: false

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set create stack
        id: createstack
        run: echo "::set-output name=createstack::$CREATE_STACK"
        env:
          CREATE_STACK: ${{ github.event_name != 'repository_dispatch' }}
      - uses: ./
        name: Deploy Stack
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          stack-name: 'richardwillis-github-action-example-cloudformation-stack'
          template: './cloudformation/s3bucket-example.yml'
          preview: true
          aws-region: 'us-east-1'
          parameters: 'S3BucketName=richardwillis.info-example-bucket-us-east-1&S3AllowedOrigins=https://richardwillis.info'
